web1:
  build: .
  expose:
    - 8000
  links:
    - redis

web2:
  build: .
  expose:
    - 8000
  links:
    - redis

web3:
  build: .
  expose:
    - 8000
  links:
    - redis

nginx:
  build: ./nginx
  links:
    - web1:web1
    - web2:web2
    - web3:web3
  ports:
    - "3000:80"

redis:
    image: redis
    ports:
        - "6379"
